CREATE TABLE ControleFinanceiro..Bill 
(Id INT NOT NULL PRIMARY KEY IDENTITY
,IdCreditCard INT NOT NULL
,DueDate DATETIME NOT NULL
,FOREIGN KEY (IdCreditCard) REFERENCES CreditCard(Id) ON DELETE CASCADE)