CREATE TABLE ControleFinanceiro..ExpenseInstallment 
(Id INT NOT NULL PRIMARY KEY IDENTITY
,IdExpense INT NOT NULL
,IdBill INT NOT NULL
,Installment SMALLINT NOT NULL
,[Status] NVARCHAR(40) NOT NULL
,ReferenceDate DATETIME NOT NULL
,[Value] DECIMAL(10,2) NOT NULL
,FOREIGN KEY (IdExpense) REFERENCES Expense(Id) ON DELETE CASCADE
,FOREIGN KEY (IdBill) REFERENCES Bill(Id) ON DELETE CASCADE)